services:
  baseline:
    image: angelacortecchia/experiments-2025-acsos-robots:${VERSION:-latest}
    build:
      context: .
      dockerfile: docker/sim/Dockerfile
    volumes:
      - angela.cortecchia-volume:/experiment/data
    environment:
      - MAX_SEED=31
      - GRADLE_TASK=runDepotsBaselineBatch

  baseline-random-failure:
    image: angelacortecchia/experiments-2025-acsos-robots:${VERSION:-latest}
    build:
      context: .
      dockerfile: docker/sim/Dockerfile
    volumes:
      - angela.cortecchia-volume:/experiment/data
    environment:
      - MAX_SEED=31
      - GRADLE_TASK=runDepotsBaselineRandomFailureBatch

  oracle:
    image: angelacortecchia/experiments-2025-acsos-robots:${VERSION:-latest}
    build:
      context: .
      dockerfile: docker/sim/Dockerfile
    volumes:
      - angela.cortecchia-volume:/experiment/data
    environment:
      - MAX_SEED=31
      - GRADLE_TASK=runDepotsOracleBatch

  oracle-random-failure:
    image: angelacortecchia/experiments-2025-acsos-robots:${VERSION:-latest}
    build:
      context: .
      dockerfile: docker/sim/Dockerfile
    volumes:
      - angela.cortecchia-volume:/experiment/data
    environment:
      - MAX_SEED=31
      - GRADLE_TASK=runDepotsOracleRandomFailureBatch

  runtime-flag-false:
    image: angelacortecchia/experiments-2025-acsos-robots:${VERSION:-latest}
    build:
      context: .
      dockerfile: docker/sim/Dockerfile
    volumes:
      - angela.cortecchia-volume:/experiment/data
    environment:
      - MAX_SEED=31
      - LEADER_BASED=false
      - GRADLE_TASK=runDepotsRuntimeBatch

  runtime-flag-true:
    image: angelacortecchia/experiments-2025-acsos-robots:${VERSION:-latest}
    build:
      context: .
      dockerfile: docker/sim/Dockerfile
    volumes:
      - angela.cortecchia-volume:/experiment/data
    environment:
      - MAX_SEED=31
      - LEADER_BASED=true
      - GRADLE_TASK=runDepotsRuntimeBatch

  runtime-random-failure-flag-false:
    image: angelacortecchia/experiments-2025-acsos-robots:${VERSION:-latest}
    build:
      context: .
      dockerfile: docker/sim/Dockerfile
    volumes:
      - angela.cortecchia-volume:/experiment/data
    environment:
      - MAX_SEED=31
      - LEADER_BASED=false
      - GRADLE_TASK=runDepotsRuntimeRandomFailureBatch

  runtime-random-failure-flag-true:
    image: angelacortecchia/experiments-2025-acsos-robots:${VERSION:-latest}
    build:
      context: .
      dockerfile: docker/sim/Dockerfile
    volumes:
      - angela.cortecchia-volume:/experiment/data
    environment:
      - MAX_SEED=31
      - LEADER_BASED=true
      - GRADLE_TASK=runDepotsRuntimeRandomFailureBatch

volumes:
  angela.cortecchia-volume:
    external: true